# NVIDIA NeMo Agent Toolkit 黑客松配置
# 支持用户自定义OpenAI兼容API

general:
  use_uvloop: true

functions:
  tavily_search:
    _type: tavily_internet_search
    description: "使用Tavily API进行实时网络搜索"
  
  current_datetime:
    _type: current_datetime
    description: "获取当前日期和时间"

  greeting_tool: # 添加新工具
    _type: greeting_tool
    description: "当用户问候'你好'时，返回带时间的问候。"

llms:
  # 默认使用Bailian API (用户可修改)
  default_llm:
    _type: openai
    model_name: "Qwen/Qwen3-30B-A3B-Thinking-2507"
    api_key: "sk-appephokhpvzsburhdgyhdnvuuqlzehzavglvdmwqudhevrd"
    # base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    base_url: "https://api.siliconflow.cn/v1"
    temperature: 0.7
    max_tokens: 2048

workflow:
  _type: react_agent
  tool_names:
    - tavily_search
    - current_datetime
    - greeting_tool # 在工作流中启用新工具

  llm_name: default_llm
  verbose: true
  parse_agent_response_max_retries: 3
  max_iterations: 10
